version: '3.8'

services:
  rtmp:
    build: .  # Dockerfile'ın bulunduğu dizini belirtin
    ports:
      - "1935:1935"  # RTMP portu
      - "80:80"      # HTTP portu
    volumes:
      - ./sy/:/usr/local/sy/recordings  # (recordings -  kayıtları bağlama)
    networks:
      rtmp_net:
        ipv4_address: 172.22.22.11
    restart: always

networks:
  rtmp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.22.0/24