services:
  rtmp:
    build: .  # Dockerfile'ın bulunduğu dizini belirtin
    ports:
      - "1935:1935"  # RTMP portu
      - "80:80"      # HTTP portu
    volumes:
      - ./sy:/usr/local/sy  # sy dizinini bağlama (livestream, recordings, scripts)
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx yapılandırma dosyasını bağlama
    command: /bin/bash -c "chown -R www-data:www-data /usr/local/sy/* && chmod +x /usr/local/sy/scripts/create-frames /usr/local/sy/scripts/handle-recording /usr/local/sy/scripts/mark-frames && nginx -g 'daemon off;'" 
    restart: always
